"""
Sensor Data Reader
Reads body composition data from CSV file generated by sensors
"""

import csv
import logging
from collections import deque
from pathlib import Path
from dataclasses import dataclass
from datetime import datetime

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    filename='fitfuel_station.log'
)


@dataclass
class SensorData:
    """Body composition data from sensors."""
    body_weight_kg: float
    skeletal_muscle_percent: float
    resting_metabolic_rate: float
    body_fat_percent: float
    timestamp: str = None
    
    def validate(self):
        """Validate sensor readings are within reasonable ranges."""
        if not (30 <= self.body_weight_kg <= 200):
            raise ValueError(f"Body weight {self.body_weight_kg}kg outside valid range (30-200kg)")
        if not (10 <= self.skeletal_muscle_percent <= 60):
            raise ValueError(f"Skeletal muscle {self.skeletal_muscle_percent}% outside valid range (10-60%)")
        if not (800 <= self.resting_metabolic_rate <= 3500):
            raise ValueError(f"RMR {self.resting_metabolic_rate} outside valid range (800-3500 kcal/day)")
        if not (5 <= self.body_fat_percent <= 60):
            raise ValueError(f"Body fat {self.body_fat_percent}% outside valid range (5-60%)")


class SensorDataReader:
    """
    Reads body composition data from CSV file generated by OMRON sensors.
    
    Expected CSV format:
    body_weight_kg,skeletal_muscle_percent,resting_metabolic_rate,body_fat_percent,timestamp
    75.5,35.2,1650,22.3,2025-01-12 14:30:00
    """
    
    def __init__(self, csv_file_path='sensor_data.csv'):
        """
        Initialize sensor data reader.
        
        Args:
            csv_file_path: Path to CSV file with sensor data
        """
        self.csv_file_path = Path(csv_file_path)
        self.logger = logging.getLogger(__name__)
    
    def read_latest_data(self):
        """
        Read the most recent sensor data from CSV file.
        
        Returns:
            SensorData: Latest sensor readings
            
        Raises:
            FileNotFoundError: If CSV file doesn't exist
            ValueError: If data is invalid
        """
        if not self.csv_file_path.exists():
            raise FileNotFoundError(
                f"Sensor data file not found: {self.csv_file_path}\n"
                f"Expecting CSV file with format:\n"
                f"body_weight_kg,skeletal_muscle_percent,resting_metabolic_rate,body_fat_percent,timestamp"
            )
        
        try:
            with open(self.csv_file_path, 'r') as file:
                reader = csv.DictReader(file)
                
                # NEW: Validate CSV headers
                required_columns = {'body_weight_kg', 'skeletal_muscle_percent', 
                                  'resting_metabolic_rate', 'body_fat_percent'}
                actual_columns = set(reader.fieldnames or [])
                
                missing = required_columns - actual_columns
                if missing:
                    raise ValueError(
                        f"CSV missing required columns: {missing}\n"
                        f"Found columns: {actual_columns}\n"
                        f"Required: {required_columns}"
                    )
                
                # Efficiently get the last row without reading everything into a list
                last_rows = deque(reader, maxlen=1)
                
                if not last_rows:
                    raise ValueError("CSV file is empty")
                
                # Get last row (most recent reading)
                latest = last_rows[0]
                
                sensor_data = SensorData(
                    body_weight_kg=float(latest['body_weight_kg']),
                    skeletal_muscle_percent=float(latest['skeletal_muscle_percent']),
                    resting_metabolic_rate=float(latest['resting_metabolic_rate']),
                    body_fat_percent=float(latest['body_fat_percent']),
                    timestamp=latest.get('timestamp', datetime.now().isoformat())
                )
                
                # Validate data
                sensor_data.validate()
                
                self.logger.info(
                    f"Sensor data loaded: Weight={sensor_data.body_weight_kg}kg, "
                    f"Muscle={sensor_data.skeletal_muscle_percent}%, "
                    f"RMR={sensor_data.resting_metabolic_rate}kcal, "
                    f"Fat={sensor_data.body_fat_percent}%"
                )
                
                return sensor_data
                
        except KeyError as e:
            raise ValueError(
                f"Missing required column in CSV: {e}\n"
                f"Expected columns: body_weight_kg, skeletal_muscle_percent, "
                f"resting_metabolic_rate, body_fat_percent, timestamp"
            )
        except ValueError as e:
            raise ValueError(f"Invalid sensor data: {e}")
    
    def create_sample_csv(self):
        """
        Create a sample CSV file for testing.
        Useful for development when sensors aren't connected.
        """
        sample_data = [
            {
                'body_weight_kg': 75.5,
                'skeletal_muscle_percent': 35.2,
                'resting_metabolic_rate': 1650,
                'body_fat_percent': 22.3,
                'timestamp': datetime.now().isoformat()
            }
        ]
        
        with open(self.csv_file_path, 'w', newline='') as file:
            fieldnames = ['body_weight_kg', 'skeletal_muscle_percent', 
                         'resting_metabolic_rate', 'body_fat_percent', 'timestamp']
            writer = csv.DictWriter(file, fieldnames=fieldnames)
            
            writer.writeheader()
            writer.writerows(sample_data)
        
        self.logger.info(f"Sample CSV created: {self.csv_file_path}")


if __name__ == "__main__":
    reader = SensorDataReader()
    if not Path('sensor_data.csv').exists():
        reader.create_sample_csv()
    data = reader.read_latest_data()
    print(f"Loaded: {data.body_weight_kg}kg, {data.skeletal_muscle_percent}% muscle")